apiVersion: v1
kind: Pod
metadata:
  name: sleepy
  namespace: default
spec:
  containers:
  - args:
    - -c
    - while true; do date; sleep 5; done
    command:
    - /bin/sh
    env:
    - name: BASE_URL
      value: https://sleepy.example.com
    image: alpine
    imagePullPolicy: Always
    name: sleep-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lf5mj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-workerpool-41980706-vmss000000
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-lf5mj
    secret:
      defaultMode: 420
      secretName: default-token-lf5mj
