apiVersion: v1
kind: ConfigMap
metadata:
  name: myappconfig
data:
  dbName: myDbName
  server: serverName
  runtimesettings.json: |
    {
      "serviceUrl": "http://localhost:8022/",
      "serviceAccount": "admservice"
    }

