apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    env: 
    - name: APP_DBNAME
      valueFrom: 
        configMapKeyRef: 
          name: myappconfig
          key: dbName
    - name: APP_SERVER
      valueFrom:
        configMapKeyRef: 
          name: myappconfig
          key: server
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /config
        name: config
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: myappconfig
        items:
          - key: runtimesettings.json
            path: runtimesettings.json
