apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspnetapp
  name: aspnetapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: aspnetapp