apiVersion: v1
kind: Secret
metadata:
  name: az-file-secret
data:
  azurestorageaccountkey: d3cvWFBQSUZHcDhFREJiNDhnaHFjVVM5RzN1VWVPekRvMmo1Nlc4dXh4bS9ycEZUVUNKdVB1UzczNkhiVnp5RndnVG5pU2ZudTNGdmlVYXZkUHEyK3c9PQ==
  azurestorageaccountname: Y2x1c3RlcnN0b3JhZ2U3NDgz
