apiVersion: v1
kind: PersistentVolume
metadata:
  name: az-file-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: az-file-secret
    shareName: filevolume
    readOnly: false
