apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
