apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-run
  name: nginx-run
spec:
  containers:
  - image: nginx
    name: nginx-run
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
