apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sleep-job
spec:
  jobTemplate:
    metadata:
      name: sleep-job
    spec:
      template:
        metadata:
          name: sleep-pod
        spec:
          containers:
          - image: busybox
            name: sleep-job
            command: ['sleep','300']
            resources: {}
          restartPolicy: OnFailure
  schedule: '* */2 * * *'
